### ISSUE TITLE
http: error: TypeError: _new_pool() got an unexpected keyword argument 'request_context'

### ISSUE THREAD

**Issue by lol768** [marklap/httpie-timing#1]
FWIW, in case anyone is trying to do this in 2019, it doesn't seem to work with version 1.0.2
